### ISSUE TITLE
Toggle pretty print successful eval result under the code

### ISSUE THREAD

**Issue by tonsky** [tonsky/Clojure-Sublimed#11]
When standing inside successful evaluation, Ctrl+I should toggle between compact one-line truncated view (first) and expanded pretty-printed view (second):

<img width="597" alt="Screenshot 2021-10-26 at 01 11 58" src="https://user-images.githubusercontent.com/285292/138783362-2c0874a1-e491-4436-91a5-5a06e3a85398.png">

Note: do not use `clojure.pprint`, better implement it yourself: same idea, but sans the part where it tries to fit keys/values into 80 chars

**Comment by aviflat** [comment]
> Note: do not use `clojure.pprint`, better implement it yourself: same idea, but sans the part where it tries to fit keys/values into 80 chars

Does `clojure.pprint/*print-right-margin*` not work for keys/values?
