### ISSUE TITLE
Empty list causes all evaluations to hang

### ISSUE THREAD

**Issue by harismh** [tonsky/Clojure-Sublimed#131]
First of all, thank you for the library. It's awesome to use. 

I was going through some examples in Joy of Clojure and noticed if you use an empty list `()` evaluating any forms after it hangs. 

<img width="454" alt="Screenshot 2024-11-02 at 15 40 04" src="https://github.com/user-attachments/assets/5976a978-a240-4136-b72f-49faa35b99aa">

Evaluating the empty list itself and any forms before it is fine. Evaluating the whole buffer works too. Commenting out the empty list fixes the issue.

<img width="472" alt="Screenshot 2024-11-02 at 15 41 05" src="https://github.com/user-attachments/assets/c11a3b98-6e3a-446a-b79f-b5f2f15baeaf">

Nothing major, I doubt any real-world code will encounter this issue. But, it is odd.

**Comment by tonsky** [comment]
Thanks! Pushed 4.3.1
