### ISSUE TITLE
Syntax highlightning incorrectly recognizes "|"

### ISSUE THREAD

**Issue by Izual13** [tonsky/Clojure-Sublimed#132]
![изображение](https://github.com/user-attachments/assets/5d57482f-8517-47e0-bcac-727eb8c889eb)

`(defn | [n1 n2] (Long/parseLong (str n1 n2)))`
`(for [o [* + |]] (o 1 2))`

**Comment by tonsky** [comment]
Technically it’s [not allowed](https://clojure.org/reference/reader) but in practice Clojure doesn’t seem to mind. Added
![Screenshot 2024-12-09 at 14 39 41](https://github.com/user-attachments/assets/ecf75035-3d2b-427d-b8a7-a5f70b5f0344)
