### ISSUE TITLE
Middleware to clone & eval in a single command

### ISSUE THREAD

**Issue by tonsky** [tonsky/Clojure-Sublimed#20]
Reduces network latency and change of errors

**Comment by jaihindhreddy** [comment]
If the intent of this is only to avoid the additional network roundtrip, then we can simply use [nREPL's ephemeral sessions](https://nrepl.org/nrepl/0.8/design/middleware.html#sessions) to do the job. This approach is implemented by #48. That being said, I did implement the other approach suggested by the literal text of the issue i.e, implementing a `clone-and-eval` middleware. This is implemented by #49.

Using Ephemeral sessions has a couple of advantages IMO:
1. Less code to make it happen (using the existing Ephemeral sessions code already provided by nREPL)
2. The one-off sessions are cleaned up (closed). Currently, an unbounded number of threads are created in the nREPL server. This could be addresses by closing the session ourselves, but the code currently does not do this (discussed separately in #50).

WDYT?

**Comment by tonsky** [comment]
Thanks! I’ll take a look after the holidays

**Comment by jaihindhreddy** [comment]
Of course! Have fun!
