### ISSUE TITLE
Syntax highlighting appears worse with Clojure Sublimed?

### ISSUE THREAD

**Issue by slifin** [tonsky/Clojure-Sublimed#63]
Hi I'm using 

```
"color_scheme": "Monokai.sublime-color-scheme",
```
Clojure Sublimed
<img width="503" alt="Screenshot 2022-01-21 at 10 31 17" src="https://user-images.githubusercontent.com/198857/150512036-dfb18a98-e5c0-47df-887b-551a07f8f9bc.png">
In-built Clojure
<img width="570" alt="Screenshot 2022-01-21 at 10 31 28" src="https://user-images.githubusercontent.com/198857/150512040-fb4f802f-f4cf-4305-8d76-58b09439d082.png">

Sorry I don't have more concrete description of the problem but does this look "correct"?

edit: the file I'm looking at is a .cljc file but this obviously reframe stuff here, I've tested with .clj files too and they have the same "problem"

**Comment by tonsky** [comment]
Clojure Sublimed might highlight less semantic stuff, yes. I personally find this enough, but do not mind if someone contribute additions

**Comment by slifin** [comment]
Ah I see, is there a way to use the nrepl client from Clojure-Sublimed with either Tutkain or sublime's inbuilt syntaxes instead?

**Comment by jaihindhreddy** [comment]
@slifin unfortunately not right now (See #24). This plugin relies on the syntax definition in order to do things like "find top form we're currently inside". If you use a different syntax, you'll see weird behaviour in any such form selection.

**Comment by jaihindhreddy** [comment]
> I personally find this enough

I second this, and prefer not having more colors TBH.

**Comment by wilkerlucio** [comment]
I also prefer the standard Clojure coloring, after getting used to semantic highlight (from Cursive in my case), the lack of them gets me lost quite often.

**Comment by tonsky** [comment]
Close in favor of #24
