### ISSUE TITLE
Clojure-Sublimed syntax breaks go-to definition of namespaced functions

### ISSUE THREAD

**Issue by jpe90** [tonsky/Clojure-Sublimed#65]
With the default Clojure syntax, go-to definition works with namespaced functions within the project. When using Clojure-Sublimed, this no longer works.

Below shows go-to definition working with default syntax on the right, not working with Clojure-Sublimed on the left, and then working in Clojure-Sublimed when the namespace is removed.

https://user-images.githubusercontent.com/9307830/152366148-1f2d2e8a-d086-4dc7-8178-2aeae7cdf974.mov

**Comment by tonsky** [comment]
Interesting! Works for me

<img width="511" alt="Screenshot 2022-02-03 at 19 05 56" src="https://user-images.githubusercontent.com/285292/152402435-dbdec788-e7ed-4f7a-b221-71383e586b58.png">

**Comment by jpe90** [comment]
Yeah that's really weird. I just checked and I can get it to work in other projects, just not one in particular. I tried clearing cache and indexes, copying the project to a new folder, but it's persisting. I'll see if I can find a way to reproduce the problem.
