### ISSUE TITLE
Parenthesis character literal is treated like list

### ISSUE THREAD

**Issue by KyleErhabor** [tonsky/Clojure-Sublimed#66]
I don't know if this is the result of using [alabaster](https://github.com/tonsky/sublime-scheme-alabaster), but given issues [here](https://github.com/tonsky/sublime-scheme-alabaster/issues/6) and [there](https://github.com/tonsky/sublime-scheme-alabaster/issues/9), it may be coming from how Clojure Sublimed treats parentheses.

When using Clojure's character literal, it's displayed correctly for most characters. For lists, however, it seems to treat the parenthesis like a character _and_ part of the form. For example, the following code prints `Klay (#3)`, but highlights the character literal as part of the `str` form. 
```clj
(def name "Klay")
(def lb-pos 3)
(println (str name " (#" lb-pos \)))
```
<img width="420" alt="Screen Shot 2022-02-12 at 7 14 51 PM" src="https://user-images.githubusercontent.com/40676441/153732966-1da603ed-e4cb-4f62-a73a-39badcfa00c7.png">
It doesn't mess with the second to last parenthesis, but it's still unpleasant to see, especially when used in long, complicated forms where a single one of these can completely change the meaning for a reader.

**Comment by tonsky** [comment]
Sorry, I don’t understand what the problem is. It seems to be highlighted correctly? Pink if for constants and this is a constant, not a parenthesis

**Comment by tonsky** [comment]
Oh, I see! It’s called bracket matching and as far as I know Sublime uses its own algorithm for that, ignoring color scheme and syntax. I have no way to affect that. It annoys the hell out of me too, sometimes
