### ISSUE TITLE
Eval results competing space with Clojure LSP

### ISSUE THREAD

**Issue by wilkerlucio** [tonsky/Clojure-Sublimed#67]
Hello, I know this is not an issue of Clojure Sublimed per see, but I couldn't find any help for this anywhere else, so I'll try to get some light here.

I'm playing with Clojure Sublime + LSP, the problem is that the LSP thing on Sublime puts an annotation to show the code actions always in the right side, for example:

<img width="1536" alt="Screen Shot 2022-02-17 at 15 09 01" src="https://user-images.githubusercontent.com/25736/154543951-06b7ed25-9822-427c-a738-caa05badaef0.png">

The result is that when I evaluate a line, it doesn't show anything on the right side. It actually does show, but it places it in a line after the LSP annotation, making it not visible... unless I hover with the mouse, like:

<img width="1536" alt="Screen Shot 2022-02-17 at 15 09 57" src="https://user-images.githubusercontent.com/25736/154544085-b2a3079f-7ba1-41ce-9ebb-3fe4d1aea52a.png">

The question is, how can I disable the LSP annotation on the right, so I can have just the Clojure Sublime evaluation there? (I still want to use code actions, but I have a dedicated shortcut for it, I just want to get rid of the annotation on the side).

**Comment by tonsky** [comment]
Ask the author of LSP plugin? They are all python, even if there’s no option to hide, it’s all pretty hackable

**Comment by wilkerlucio** [comment]
Thanks, just found it, for anyone that gets in the same situation, this is the setting to change:

`"show_code_actions": "bulb"`
