### ISSUE TITLE
How to function without autocomplete

### ISSUE THREAD

**Issue by brettrowberry** [tonsky/Clojure-Sublimed#69]
> Autocomplete. Static analysis is much simpler and much more reliable than requiring an always-live connection to the working app.

I've been a Calva (and Clojure) user for about a year and I really like it.

I'm trying out Clojure-Sublimed for the first time today. The clean stacktraces lured me in! This is a real question: How does a person function without autocomplete?

**Comment by tonsky** [comment]
I personally rely on Sublime’s autocomple

**Comment by brettrowberry** [comment]
Oh, maybe I was doing something wrong because I didn't see any autocomplete from Sublime or Clojure-Sublimed.

**Comment by tonsky** [comment]
See #40 and README
