### ISSUE TITLE
Option to display results inline with Phantoms instead of Annotations

### ISSUE THREAD

**Issue by tonsky** [tonsky/Clojure-Sublimed#8]
Might actually be two options: display right next to form (moves text after):

![Untitled](https://user-images.githubusercontent.com/285292/138782670-dcbd1bcb-171d-4538-a488-c814ea8042b6.png)

or at the end of the current line:

<img width="360" alt="Screenshot 2021-10-26 at 01 02 13" src="https://user-images.githubusercontent.com/285292/138782677-c141bad8-bc40-4cf8-a74b-9cc7ae9d83ca.png">

**Comment by jaihindhreddy** [comment]
In case you're looking for opinions, end of current line seems better to me because the users don't have to (mentally) filter out the "edits" made by the plugin, so to speak.

Seeing results closer to the code does sound very good.

**Comment by tonsky** [comment]
I think it’s great as it is now too. I was worried that it might feel a bit disconnected or hard to locate but after using it I see no problems whatsoever with the current approach.
