### ISSUE TITLE
Keymaps

### ISSUE THREAD

**Issue by wundervaflja** [tonsky/Clojure-Sublimed#84]
Sorry for openning issue. But this is more like to ask question.

 After installing `Clojure Sublimed` I couldn't find keymap preferences in `Preferences` menu. Also keybinding metioned in Readme were not working. After checking codebase I've noticed that `.sublime-keymap` files are commented out and when I've uncommented them everything worked.
 
Is it as intended? or I missed something?

**Comment by tonsky** [comment]
As far as I know, extension should not ship keybindings, because then you would have no way to disable them. That’s Sublime Text limitation. The way extension authors get around that is they ship .sublime-keymap files as an example that you can use to copy to your own local keybindings

**Comment by wundervaflja** [comment]
Apologize then for my miss understanding of your post. Will follow your advice
