### ISSUE TITLE
format_on_save may mess up non-clojure files when using save_on_focus_lost

### ISSUE THREAD

**Issue by einars** [tonsky/Clojure-Sublimed#87]
To reproduce,
1. enable global save_on_focus_lost and clojure-sublimed format_on_save,
2. in one tab open any clojure file, in other — something different, like a readme or a python code, preferably with some lines starting with whitespace to easier observe the issue,
3. edit clojure code
4. ctrl-tab to switch to the other file.

As an effect, all the lines in this file are immediately getting trimmed and edit menu shows "Undo Clojure Sublimed Reindent Buffer".

It happens because in the background the save_on_focus_lost triggers to save the clojure changes, `on_pre_save` hook runs — but it runs the command on view.window(), and the window has already switched to the other file.

Is there any particular reason for the command has to be run on view.window(), not on the view itself?

https://github.com/tonsky/Clojure-Sublimed/blob/e5ff2852a89e1bf4c0729fb994637d39cb0f612e/package.py#L970-L973

**Comment by tonsky** [comment]
Probably a bug, thanks!
