### ISSUE TITLE
Feature Request: Make nRepl Client compatible with Babashka

### ISSUE THREAD

**Issue by 7tupel** [tonsky/Clojure-Sublimed#89]
**Please Describe The Problem To Be Solved**
As of now the nRepl client of clojure-sublimed is not compatible with the the nRepl server included in Babashka.

**Suggest A Solution**
It would be great to be able to run Babashka code directly from sublime using the clojure-sublimed nRepl client.

**Comment by tonsky** [comment]
I think #83 should get you covered once it’s implemented. I plan to!

**Comment by tonsky** [comment]
Should now be possible with Connect to Raw nREPL command in 3.0.0
