### ISSUE TITLE
HiDPI - results shifted

### ISSUE THREAD

**Issue by sergey-sign** [tonsky/Clojure-Sublimed#93]
I'm not sure if this is a bug or gap of sublime or my KDE settings.
With settings `"ui_scale": 2.0` results are not fully displayed - they are shifted over the edge of the buffer. 
But with `"ui_scale": 0.0` and environment variable `GDK_SCALE=2` they look like expected.

![subl_ui_scale2](https://user-images.githubusercontent.com/681721/226207210-6d96cd14-305d-4486-abdc-da8dde3f476f.png)
![subl_ui_scale0](https://user-images.githubusercontent.com/681721/226207207-79511843-18c5-4944-aa09-ab117f474193.png)

sublime build 4143

**Comment by tonsky** [comment]
Please report it to the Sublime Text
