### ISSUE TITLE
Some of the Tutkain bits in the README are out of date

### ISSUE THREAD

**Issue by eerohele** [tonsky/Clojure-Sublimed#97]
Hi there!

Just thought I'd pop by to say that some of the Tutkain bits in the README are out of date:

>- Does not have separate REPL panel

Tutkain doesn't force you to use a separate REPL panel. You can operate entirely using inline results if you prefer. (The UI definitely isn't geared toward that at the moment, though.)

>- Keeps multiple eval results on a screen simultaneously

Tutkain also does, albeit in the output panel, instead of inline. :) But yes, this is true, for the time being, at least.

>- Can show stack traces inline in editor
>- Can eval several forms in parallel

These still hold.

>- Can eval non well-formed forms (e.g. (+ 1 2)

Tutkain now has [an RPC-style connection mode](https://tutkain.flowthing.me/#choosing-connection-mode) that has this behavior.

>- Can eval infinite sequences

The approach Tutkain currently recommend is to have a an [`init`](https://tutkain.flowthing.me/#customizing-your-repl) function where you set `*print-length*` to your preferred value.

>- Redirects all *out*/*err* to System.out/System.err

Tutkain lets you do this as well (although it could be a bit less of a hassle).

I don't mind having comparisons in Tutkain in the README and I do see their value, but with the exception of parallel evals, almost none of the things currently listed there are set in stone and are subject to change/improvement.

In any case, great work on Clojure Sublimed — it looks fantastic! It's great to have options for using Sublime Text for Clojure programming. 👍🏻

**Comment by tonsky** [comment]
If you are actively working on it, it might get stale pretty quickly, so I removed it altogether. It was mostly for myself to rationalize why I’m making another REPL anyway :)

**Comment by eerohele** [comment]
>for myself to rationalize why I’m making another REPL anyway :)

Yep, totally get that. :) Thanks!
